import { Module } from '../../types';

export const MODULE_1: Module = {
  id: '1',
  title: 'Asuhan Kehamilan (ANC)',
  category: 'Kehamilan',
  color: '#F687B3',
  progress: 0.75,
  videos: 15,
  duration: '3 jam 45 menit',
  difficulty: 'beginner',
  introVideoId: 'M7lc1UVf-VE',
  description: 'Modul ini membahas tentang pemeriksaan Antenatal Care (ANC) yang bertujuan untuk memantau kesehatan ibu hamil dan perkembangan janin selama masa kehamilan.',
  objectives: [
    'Memahami konsep dan tujuan pemeriksaan ANC',
    'Menguasai teknik pemeriksaan fisik ibu hamil',
    'Mampu melakukan edukasi kesehatan pada ibu hamil',
    'Mengenali tanda bahaya kehamilan dan penanganannya',
    'Melakukan pemeriksaan Leopold dengan benar',
  ],
  learningOutcomes: [
    'Mahasiswa mampu melakukan pemeriksaan ANC sesuai standar',
    'Mahasiswa dapat memberikan edukasi yang tepat pada ibu hamil',
    'Mahasiswa mampu mendeteksi dini komplikasi kehamilan',
  ],
  chapters: [
    {
      id: 'ch1-1',
      title: 'Dasar-dasar ANC',
      description: 'Pengenalan konsep dan prosedur dasar pemeriksaan antenatal care',
      order: 1,
      lessons: [
        { id: '1-1', title: 'Pendahuluan ANC', duration: '8:32', videoId: 'oDtprarpHwg', description: 'Pengenalan konsep ANC', order: 1, isCompleted: true },
        { id: '1-2', title: 'Riwayat Kehamilan', duration: '12:10', videoId: 'D3qVhy3LvdY', description: 'Cara mengambil riwayat kehamilan', order: 2, isCompleted: true },
        { id: '1-3', title: 'Pemeriksaan Fisik Umum', duration: '10:45', videoId: 'M7lc1UVf-VE', description: 'Teknik pemeriksaan fisik umum', order: 3, isCompleted: false },
        { id: '1-4', title: 'Pemeriksaan Tanda Vital', duration: '9:15', videoId: 'oDtprarpHwg', description: 'Pengukuran tekanan darah, nadi, suhu', order: 4, isCompleted: false },
        { id: '1-5', title: 'Pemeriksaan Antropometri', duration: '7:30', videoId: 'D3qVhy3LvdY', description: 'Pengukuran berat badan, tinggi badan', order: 5, isCompleted: false },
      ],
    },
    {
      id: 'ch1-2',
      title: 'Pemeriksaan Khusus Kehamilan',
      description: 'Teknik pemeriksaan spesifik untuk memantau kondisi kehamilan',
      order: 2,
      lessons: [
        { id: '1-6', title: 'Pemeriksaan Leopold I', duration: '9:20', videoId: 'M7lc1UVf-VE', description: 'Teknik Leopold I', order: 6, isCompleted: false },
        { id: '1-7', title: 'Pemeriksaan Leopold II', duration: '8:45', videoId: 'oDtprarpHwg', description: 'Teknik Leopold II', order: 7, isCompleted: false },
        { id: '1-8', title: 'Pemeriksaan Leopold III', duration: '7:50', videoId: 'D3qVhy3LvdY', description: 'Teknik Leopold III', order: 8, isCompleted: false },
        { id: '1-9', title: 'Pemeriksaan Leopold IV', duration: '8:15', videoId: 'M7lc1UVf-VE', description: 'Teknik Leopold IV', order: 9, isCompleted: false },
        { id: '1-10', title: 'Pengukuran TFU', duration: '7:15', videoId: 'oDtprarpHwg', description: 'Cara mengukur tinggi fundus uteri', order: 10, isCompleted: false },
      ],
    },
    {
      id: 'ch1-3',
      title: 'Pemantauan Janin',
      description: 'Teknik pemantauan kondisi dan kesejahteraan janin',
      order: 3,
      lessons: [
        { id: '1-11', title: 'Pemeriksaan DJJ Manual', duration: '8:50', videoId: 'D3qVhy3LvdY', description: 'Mendengar DJJ dengan stetoskop', order: 11, isCompleted: false },
        { id: '1-12', title: 'Pemeriksaan DJJ Doppler', duration: '10:30', videoId: 'M7lc1UVf-VE', description: 'Penggunaan doppler untuk DJJ', order: 12, isCompleted: false },
        { id: '1-13', title: 'Penilaian Gerakan Janin', duration: '9:40', videoId: 'oDtprarpHwg', description: 'Cara menilai gerakan janin', order: 13, isCompleted: false },
        { id: '1-14', title: 'Deteksi Tanda Bahaya', duration: '11:25', videoId: 'D3qVhy3LvdY', description: 'Mengenali tanda bahaya kehamilan', order: 14, isCompleted: false },
        { id: '1-15', title: 'Dokumentasi ANC', duration: '6:45', videoId: 'M7lc1UVf-VE', description: 'Cara mendokumentasikan hasil ANC', order: 15, isCompleted: false },
      ],
    },
  ],
  steps: [
    { id: 'step1-1', title: 'Persiapan Alat dan Lingkungan', detail: 'Pastikan alat pemeriksaan siap dan area pemeriksaan bersih serta nyaman.', order: 1, isImportant: true, tips: ['Pastikan pencahayaan cukup', 'Cuci tangan sebelum pemeriksaan'] },
    { id: 'step1-2', title: 'Identifikasi dan Anamnesis', detail: 'Lakukan identifikasi pasien dan wawancara mengenai usia kehamilan dan riwayat kesehatan.', order: 2, isImportant: true, tips: ['Gunakan bahasa yang mudah dipahami', 'Tanyakan riwayat kehamilan sebelumnya'] },
    { id: 'step1-3', title: 'Pemeriksaan Tanda Vital', detail: 'Ukur tekanan darah, nadi, suhu tubuh, dan frekuensi pernapasan.', order: 3, isImportant: true, tips: ['Ukur tekanan darah dalam posisi duduk'] },
    { id: 'step1-4', title: 'Pemeriksaan Leopold', detail: 'Lakukan pemeriksaan Leopold I-IV secara berurutan.', order: 4, isImportant: true, tips: ['Lakukan dengan tangan hangat', 'Minta ibu untuk rileks'] },
    { id: 'step1-5', title: 'Pemeriksaan DJJ', detail: 'Dengarkan denyut jantung janin menggunakan stetoskop atau doppler.', order: 5, isImportant: true, tips: ['DJJ normal 120-160 x/menit'] },
    { id: 'step1-6', title: 'Edukasi dan Dokumentasi', detail: 'Berikan edukasi dan catat semua hasil pemeriksaan dalam rekam medis.', order: 6, isImportant: true, tips: ['Berikan buku KIA', 'Jadwalkan kunjungan berikutnya'] },
  ],
  tools: [
    { id: 'tool1-1', name: 'Tensimeter', description: 'Untuk mengukur tekanan darah', category: 'primary' },
    { id: 'tool1-2', name: 'Stetoskop', description: 'Untuk mendengar DJJ', category: 'primary' },
    { id: 'tool1-3', name: 'Timbangan', description: 'Untuk mengukur berat badan', category: 'primary' },
    { id: 'tool1-4', name: 'Pita Ukur', description: 'Untuk mengukur TFU dan LILA', category: 'primary' },
    { id: 'tool1-5', name: 'Doppler', description: 'Untuk mendengar DJJ', category: 'primary' },
    { id: 'tool1-6', name: 'Sarung Tangan', description: 'Untuk kebersihan pemeriksaan', category: 'primary' },
    { id: 'tool1-7', name: 'Thermometer', description: 'Untuk mengukur suhu tubuh', category: 'secondary' },
    { id: 'tool1-8', name: 'Buku KIA', description: 'Untuk dokumentasi dan edukasi', category: 'secondary' },
  ],
};